version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(deps):"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: .sage
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(deps):"
    groups:
      all-dependencies:
        patterns:
          - "*"
