steps:
  - id: fetch github token
    name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - "gcloud secrets versions access latest --secret=einride-bot-github-token --project=einride-terraform > github.token"

  - id: setup git credentials
    name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo -e "https://git:$(cat github.token)@github.com" > $${HOME}/.git-credentials \
        && git config --global credential.helper store \
        && git fetch --unshallow
    volumes:
      - name: "home-folder"
        path: /root

  - id: make
    name: golang:1.16
    args: ["make"]

  - id: release go binaries
    name: goreleaser/goreleaser
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - 'export GITHUB_TOKEN="$(cat github.token)" && goreleaser'
    volumes:
      - name: "home-folder"
        path: /root
