name: Release
on:
  push:
    branches: [master]
permissions: write-all
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Sage
        uses: einride/sage/actions/setup@master

      - name: Make
        run: make

      - name: Release
        id: release
        uses: go-semantic-release/action@v1.21.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true

      - name: Fetch tags
        if: steps.release.outputs.version != ''
        run: git fetch --force --tags

      - name: Run goreleaser
        if: steps.release.outputs.version != ''
        uses: goreleaser/goreleaser-action@v4.3.0
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
